# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Cliente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("color:rgb(200, 200, 255);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 800))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_popup = QtWidgets.QFrame(self.top_bar)
        self.frame_popup.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_popup.setStyleSheet("background-color: rgb(57, 173, 84);\n"
"border-radius:5px;")
        self.frame_popup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_popup.setObjectName("frame_popup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_popup)
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_popup)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(35, 35, 35);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame_popup)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close_Image/Images/cil-x.png);\n"
"    background-position:center;\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame_popup)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editocli_area = QtWidgets.QFrame(self.content)
        self.editocli_area.setMinimumSize(QtCore.QSize(0, 0))
        self.editocli_area.setMaximumSize(QtCore.QSize(950, 700))
        self.editocli_area.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 10px")
        self.editocli_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editocli_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editocli_area.setObjectName("editocli_area")
        self.logo = QtWidgets.QFrame(self.editocli_area)
        self.logo.setGeometry(QtCore.QRect(410, 0, 211, 90))
        self.logo.setStyleSheet("background-image: url(:/Logo_yellow/Images/logorocha_360x90.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.btn_return = QtWidgets.QPushButton(self.editocli_area)
        self.btn_return.setGeometry(QtCore.QRect(30, 20, 41, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_return.setObjectName("btn_return")
        self.txt_id = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_id.setGeometry(QtCore.QRect(510, 80, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_id.setFont(font)
        self.txt_id.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_id.setMaxLength(64)
        self.txt_id.setObjectName("txt_id")
        self.btn_search = QtWidgets.QPushButton(self.editocli_area)
        self.btn_search.setGeometry(QtCore.QRect(410, 80, 41, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"    font: 18pt ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.txt_nome = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_nome.setGeometry(QtCore.QRect(10, 80, 391, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_nome.setFont(font)
        self.txt_nome.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_nome.setMaxLength(32)
        self.txt_nome.setObjectName("txt_nome")
        self.txt_clinacionalidade = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clinacionalidade.setGeometry(QtCore.QRect(730, 440, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clinacionalidade.setFont(font)
        self.txt_clinacionalidade.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clinacionalidade.setMaxLength(32)
        self.txt_clinacionalidade.setObjectName("txt_clinacionalidade")
        self.txt_cliestadocivil = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_cliestadocivil.setGeometry(QtCore.QRect(730, 500, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_cliestadocivil.setFont(font)
        self.txt_cliestadocivil.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_cliestadocivil.setMaxLength(32)
        self.txt_cliestadocivil.setObjectName("txt_cliestadocivil")
        self.txt_clibairro = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clibairro.setGeometry(QtCore.QRect(510, 320, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clibairro.setFont(font)
        self.txt_clibairro.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clibairro.setMaxLength(64)
        self.txt_clibairro.setObjectName("txt_clibairro")
        self.txt_clinumero = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clinumero.setGeometry(QtCore.QRect(730, 320, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clinumero.setFont(font)
        self.txt_clinumero.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clinumero.setMaxLength(32)
        self.txt_clinumero.setObjectName("txt_clinumero")
        self.txt_clicidade = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clicidade.setGeometry(QtCore.QRect(510, 380, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clicidade.setFont(font)
        self.txt_clicidade.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clicidade.setMaxLength(32)
        self.txt_clicidade.setObjectName("txt_clicidade")
        self.txt_cliend = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_cliend.setGeometry(QtCore.QRect(510, 260, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_cliend.setFont(font)
        self.txt_cliend.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_cliend.setMaxLength(64)
        self.txt_cliend.setObjectName("txt_cliend")
        self.txt_clinome = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clinome.setGeometry(QtCore.QRect(510, 140, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clinome.setFont(font)
        self.txt_clinome.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clinome.setMaxLength(64)
        self.txt_clinome.setObjectName("txt_clinome")
        self.txt_clicep = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clicep.setGeometry(QtCore.QRect(510, 440, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clicep.setFont(font)
        self.txt_clicep.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clicep.setMaxLength(32)
        self.txt_clicep.setObjectName("txt_clicep")
        self.txt_cliemail = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_cliemail.setGeometry(QtCore.QRect(730, 560, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_cliemail.setFont(font)
        self.txt_cliemail.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_cliemail.setMaxLength(32)
        self.txt_cliemail.setObjectName("txt_cliemail")
        self.txt_clirg = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clirg.setGeometry(QtCore.QRect(730, 200, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clirg.setFont(font)
        self.txt_clirg.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clirg.setMaxLength(32)
        self.txt_clirg.setObjectName("txt_clirg")
        self.txt_cliestado = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_cliestado.setGeometry(QtCore.QRect(730, 380, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_cliestado.setFont(font)
        self.txt_cliestado.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_cliestado.setMaxLength(32)
        self.txt_cliestado.setObjectName("txt_cliestado")
        self.txt_obranumero_7 = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obranumero_7.setGeometry(QtCore.QRect(510, 560, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obranumero_7.setFont(font)
        self.txt_obranumero_7.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obranumero_7.setMaxLength(32)
        self.txt_obranumero_7.setObjectName("txt_obranumero_7")
        self.txt_clicpf = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_clicpf.setGeometry(QtCore.QRect(510, 200, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_clicpf.setFont(font)
        self.txt_clicpf.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_clicpf.setMaxLength(32)
        self.txt_clicpf.setObjectName("txt_clicpf")
        self.txt_cliprofissao = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_cliprofissao.setGeometry(QtCore.QRect(510, 500, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_cliprofissao.setFont(font)
        self.txt_cliprofissao.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_cliprofissao.setMaxLength(32)
        self.txt_cliprofissao.setObjectName("txt_cliprofissao")
        self.tabWid_cli = QtWidgets.QTableWidget(self.editocli_area)
        self.tabWid_cli.setGeometry(QtCore.QRect(10, 140, 491, 471))
        self.tabWid_cli.setStyleSheet("QTableWidget{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QTableWidget:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QTableWidget:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QTableWidget:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: rgb(255, 165, 24);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton {\n"
"    background-color: rgb(30, 30, 30); \n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.tabWid_cli.setObjectName("tabWid_cli")
        self.tabWid_cli.setColumnCount(15)
        self.tabWid_cli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(14, item)
        self.btn_submit_2 = QtWidgets.QPushButton(self.editocli_area)
        self.btn_submit_2.setGeometry(QtCore.QRect(640, 630, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_submit_2.setFont(font)
        self.btn_submit_2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_submit_2.setObjectName("btn_submit_2")
        self.btn_delete = QtWidgets.QPushButton(self.editocli_area)
        self.btn_delete.setGeometry(QtCore.QRect(40, 630, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.btn_edit = QtWidgets.QPushButton(self.editocli_area)
        self.btn_edit.setGeometry(QtCore.QRect(340, 630, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_edit.setFont(font)
        self.btn_edit.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_edit.setObjectName("btn_edit")
        self.btn_search_2 = QtWidgets.QPushButton(self.editocli_area)
        self.btn_search_2.setGeometry(QtCore.QRect(460, 80, 41, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search_2.setFont(font)
        self.btn_search_2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"    font: 18pt ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_search_2.setObjectName("btn_search_2")
        self.horizontalLayout.addWidget(self.editocli_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setContentsMargins(0, 0, 6, 1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_version = QtWidgets.QLabel(self.bottom)
        self.lbl_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout_2.addWidget(self.lbl_version)
        self.lbl_created = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.lbl_created.setFont(font)
        self.lbl_created.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_created.setObjectName("lbl_created")
        self.verticalLayout_2.addWidget(self.lbl_created)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit Client"))
        self.label.setText(_translate("MainWindow", "EDITADO"))
        self.btn_return.setText(_translate("MainWindow", "↩"))
        self.txt_id.setPlaceholderText(_translate("MainWindow", "DIGITE O ID"))
        self.btn_search.setText(_translate("MainWindow", "⌕"))
        self.txt_nome.setPlaceholderText(_translate("MainWindow", "NOME DO CLIENTE"))
        self.txt_clinacionalidade.setPlaceholderText(_translate("MainWindow", "NACIONALIDADE"))
        self.txt_cliestadocivil.setPlaceholderText(_translate("MainWindow", "ESTADO CIVIL"))
        self.txt_clibairro.setPlaceholderText(_translate("MainWindow", "BAIRRO"))
        self.txt_clinumero.setPlaceholderText(_translate("MainWindow", "NUMERO"))
        self.txt_clicidade.setPlaceholderText(_translate("MainWindow", "CIDADE"))
        self.txt_cliend.setPlaceholderText(_translate("MainWindow", "ENDEREÇO"))
        self.txt_clinome.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.txt_clicep.setPlaceholderText(_translate("MainWindow", "CEP"))
        self.txt_cliemail.setPlaceholderText(_translate("MainWindow", "EMAIL"))
        self.txt_clirg.setPlaceholderText(_translate("MainWindow", "RG"))
        self.txt_cliestado.setPlaceholderText(_translate("MainWindow", "ESTADO"))
        self.txt_obranumero_7.setPlaceholderText(_translate("MainWindow", "CELULAR"))
        self.txt_clicpf.setPlaceholderText(_translate("MainWindow", "CPF"))
        self.txt_cliprofissao.setPlaceholderText(_translate("MainWindow", "PROFISSÃO"))
        item = self.tabWid_cli.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabWid_cli.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tabWid_cli.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tabWid_cli.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RG"))
        item = self.tabWid_cli.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ENDEREÇO"))
        item = self.tabWid_cli.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "BAIRRO"))
        item = self.tabWid_cli.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "NUM"))
        item = self.tabWid_cli.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CIDADE"))
        item = self.tabWid_cli.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ESTADO"))
        item = self.tabWid_cli.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "CEP"))
        item = self.tabWid_cli.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "NACIONALIDADE"))
        item = self.tabWid_cli.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "PROFISSÃO"))
        item = self.tabWid_cli.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "ESTADO CIVIL"))
        item = self.tabWid_cli.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "ValorVisita"))
        item = self.tabWid_cli.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "EMAIL"))
        self.btn_submit_2.setText(_translate("MainWindow", "ADD"))
        self.btn_delete.setText(_translate("MainWindow", "DELETE"))
        self.btn_edit.setText(_translate("MainWindow", "EDIT"))
        self.btn_search_2.setText(_translate("MainWindow", "⟳"))
        self.lbl_version.setText(_translate("MainWindow", "V 1.1"))
        self.lbl_created.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">Created by Gustavo Lima</span></p></body></html>"))
import file_rc_rc
