# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'make_doc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Doc(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 870)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 870))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("color:rgb(200, 200, 255);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_popup = QtWidgets.QFrame(self.top_bar)
        self.frame_popup.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_popup.setStyleSheet("background-color: rgb(57, 173, 84);\n"
"border-radius:5px;")
        self.frame_popup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_popup.setObjectName("frame_popup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_popup)
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_popup = QtWidgets.QLabel(self.frame_popup)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.lbl_popup.setFont(font)
        self.lbl_popup.setStyleSheet("color: rgb(35, 35, 35);")
        self.lbl_popup.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_popup.setObjectName("lbl_popup")
        self.horizontalLayout_3.addWidget(self.lbl_popup)
        self.pushButton = QtWidgets.QPushButton(self.frame_popup)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close_Image/Images/cil-x.png);\n"
"    background-position:center;\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame_popup)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.makedoc_area = QtWidgets.QFrame(self.content)
        self.makedoc_area.setMaximumSize(QtCore.QSize(950, 765))
        self.makedoc_area.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 10px")
        self.makedoc_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.makedoc_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.makedoc_area.setObjectName("makedoc_area")
        self.logo = QtWidgets.QFrame(self.makedoc_area)
        self.logo.setGeometry(QtCore.QRect(360, 0, 211, 90))
        self.logo.setStyleSheet("background-image: url(:/Logo_yellow/Images/logorocha_360x90.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.cbox_1cli = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_1cli.setGeometry(QtCore.QRect(520, 430, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_1cli.setFont(font)
        self.cbox_1cli.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_1cli.setObjectName("cbox_1cli")
        self.cbox_2cli = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_2cli.setGeometry(QtCore.QRect(520, 460, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_2cli.setFont(font)
        self.cbox_2cli.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_2cli.setObjectName("cbox_2cli")
        self.cbox_3cli = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_3cli.setGeometry(QtCore.QRect(740, 430, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_3cli.setFont(font)
        self.cbox_3cli.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_3cli.setObjectName("cbox_3cli")
        self.cbox_4cli = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_4cli.setGeometry(QtCore.QRect(740, 460, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_4cli.setFont(font)
        self.cbox_4cli.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_4cli.setObjectName("cbox_4cli")
        self.cbox_memorial = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_memorial.setGeometry(QtCore.QRect(520, 240, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_memorial.setFont(font)
        self.cbox_memorial.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_memorial.setObjectName("cbox_memorial")
        self.cbox_memorialcontrucao = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_memorialcontrucao.setGeometry(QtCore.QRect(520, 270, 411, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_memorialcontrucao.setFont(font)
        self.cbox_memorialcontrucao.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_memorialcontrucao.setObjectName("cbox_memorialcontrucao")
        self.cbox_procuracao = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_procuracao.setGeometry(QtCore.QRect(520, 180, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_procuracao.setFont(font)
        self.cbox_procuracao.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_procuracao.setObjectName("cbox_procuracao")
        self.cbox_reqslei = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_reqslei.setGeometry(QtCore.QRect(520, 210, 221, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_reqslei.setFont(font)
        self.cbox_reqslei.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_reqslei.setObjectName("cbox_reqslei")
        self.cbox_reqclei = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_reqclei.setGeometry(QtCore.QRect(740, 210, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_reqclei.setFont(font)
        self.cbox_reqclei.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_reqclei.setObjectName("cbox_reqclei")
        self.cbox_declaracao = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_declaracao.setGeometry(QtCore.QRect(740, 180, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_declaracao.setFont(font)
        self.cbox_declaracao.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_declaracao.setObjectName("cbox_declaracao")
        self.cbox_contrato = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_contrato.setGeometry(QtCore.QRect(520, 150, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_contrato.setFont(font)
        self.cbox_contrato.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_contrato.setObjectName("cbox_contrato")
        self.cbox_recibo = QtWidgets.QCheckBox(self.makedoc_area)
        self.cbox_recibo.setGeometry(QtCore.QRect(740, 150, 211, 22))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.cbox_recibo.setFont(font)
        self.cbox_recibo.setStyleSheet("QCheckBox::indicator{\n"
"    border: 3px solid rgb(100, 100, 100);\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(135, 135, 135);\n"
"}\n"
"QCheckBox::indicator:checked{\n"
"    border: 3px solid rgb(195, 156, 0);\n"
"    background-color: rgb(255, 255, 127);\n"
"}")
        self.cbox_recibo.setObjectName("cbox_recibo")
        self.btn_make = QtWidgets.QPushButton(self.makedoc_area)
        self.btn_make.setGeometry(QtCore.QRect(580, 690, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_make.setFont(font)
        self.btn_make.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_make.setObjectName("btn_make")
        self.btn_return = QtWidgets.QPushButton(self.makedoc_area)
        self.btn_return.setGeometry(QtCore.QRect(30, 20, 41, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_return.setObjectName("btn_return")
        self.tabWid_obra = QtWidgets.QTableWidget(self.makedoc_area)
        self.tabWid_obra.setGeometry(QtCore.QRect(10, 150, 491, 271))
        self.tabWid_obra.setStyleSheet("QTableWidget{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QTableWidget:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QTableWidget:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QTableWidget:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: rgb(255, 165, 24);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton {\n"
"    background-color: rgb(30, 30, 30); \n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.tabWid_obra.setObjectName("tabWid_obra")
        self.tabWid_obra.setColumnCount(20)
        self.tabWid_obra.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(19, item)
        self.tabWid_cli = QtWidgets.QTableWidget(self.makedoc_area)
        self.tabWid_cli.setGeometry(QtCore.QRect(10, 490, 491, 271))
        self.tabWid_cli.setStyleSheet("QTableWidget{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QTableWidget:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QTableWidget:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QTableWidget:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: rgb(255, 165, 24);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton {\n"
"    background-color: rgb(30, 30, 30); \n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.tabWid_cli.setObjectName("tabWid_cli")
        self.tabWid_cli.setColumnCount(15)
        self.tabWid_cli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_cli.setHorizontalHeaderItem(14, item)
        self.txt_searchrua = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_searchrua.setGeometry(QtCore.QRect(10, 90, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_searchrua.setFont(font)
        self.txt_searchrua.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_searchrua.setMaxLength(32)
        self.txt_searchrua.setObjectName("txt_searchrua")
        self.btn_search = QtWidgets.QPushButton(self.makedoc_area)
        self.btn_search.setGeometry(QtCore.QRect(450, 90, 51, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.btn_search_2 = QtWidgets.QPushButton(self.makedoc_area)
        self.btn_search_2.setGeometry(QtCore.QRect(450, 430, 51, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        self.btn_search_2.setFont(font)
        self.btn_search_2.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_search_2.setObjectName("btn_search_2")
        self.txt_searchnome = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_searchnome.setGeometry(QtCore.QRect(10, 430, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_searchnome.setFont(font)
        self.txt_searchnome.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_searchnome.setMaxLength(32)
        self.txt_searchnome.setObjectName("txt_searchnome")
        self.txt_idobra = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_idobra.setGeometry(QtCore.QRect(510, 490, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idobra.setFont(font)
        self.txt_idobra.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idobra.setMaxLength(32)
        self.txt_idobra.setObjectName("txt_idobra")
        self.txt_idcli1 = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_idcli1.setGeometry(QtCore.QRect(510, 550, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli1.setFont(font)
        self.txt_idcli1.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli1.setMaxLength(32)
        self.txt_idcli1.setObjectName("txt_idcli1")
        self.txt_idcli2 = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_idcli2.setGeometry(QtCore.QRect(730, 550, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli2.setFont(font)
        self.txt_idcli2.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli2.setMaxLength(32)
        self.txt_idcli2.setObjectName("txt_idcli2")
        self.txt_idcli3 = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_idcli3.setGeometry(QtCore.QRect(510, 610, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli3.setFont(font)
        self.txt_idcli3.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli3.setMaxLength(32)
        self.txt_idcli3.setObjectName("txt_idcli3")
        self.txt_idcli4 = QtWidgets.QLineEdit(self.makedoc_area)
        self.txt_idcli4.setGeometry(QtCore.QRect(730, 610, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli4.setFont(font)
        self.txt_idcli4.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli4.setMaxLength(32)
        self.txt_idcli4.setObjectName("txt_idcli4")
        self.horizontalLayout.addWidget(self.makedoc_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setContentsMargins(0, 0, 6, 1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_version = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.lbl_version.setFont(font)
        self.lbl_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout_2.addWidget(self.lbl_version)
        self.label = QtWidgets.QLabel(self.bottom)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Make Doc"))
        self.lbl_popup.setText(_translate("MainWindow", "FEITO!"))
        self.cbox_1cli.setText(_translate("MainWindow", "UM CLIENTE"))
        self.cbox_2cli.setText(_translate("MainWindow", "DOIS CLIENTES"))
        self.cbox_3cli.setText(_translate("MainWindow", "TRÊS CLIENTES"))
        self.cbox_4cli.setText(_translate("MainWindow", "QUATRO CLIENTES"))
        self.cbox_memorial.setText(_translate("MainWindow", "MEMORIAL DESCRITIVO"))
        self.cbox_memorialcontrucao.setText(_translate("MainWindow", "MEMORIAL P/ CONSTRUÇÃO"))
        self.cbox_procuracao.setText(_translate("MainWindow", "PROCURAÇÃO"))
        self.cbox_reqslei.setText(_translate("MainWindow", "REQUERIMENTO S/ LEI"))
        self.cbox_reqclei.setText(_translate("MainWindow", "REQUERIMENTO C/ LEI"))
        self.cbox_declaracao.setText(_translate("MainWindow", "DECLARAÇÃO"))
        self.cbox_contrato.setText(_translate("MainWindow", "CONTRATO"))
        self.cbox_recibo.setText(_translate("MainWindow", "RECIBO"))
        self.btn_make.setText(_translate("MainWindow", "MAKE"))
        self.btn_return.setText(_translate("MainWindow", "↩"))
        item = self.tabWid_obra.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabWid_obra.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ENDEREÇO"))
        item = self.tabWid_obra.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "BAIRRO"))
        item = self.tabWid_obra.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NUMERO"))
        item = self.tabWid_obra.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CIDADE"))
        item = self.tabWid_obra.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "LOTE"))
        item = self.tabWid_obra.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "QUADRA"))
        item = self.tabWid_obra.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "QUARTEIRÃO"))
        item = self.tabWid_obra.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.tabWid_obra.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "AREA"))
        item = self.tabWid_obra.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "ART"))
        item = self.tabWid_obra.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "VALOR PARCELA"))
        item = self.tabWid_obra.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "QUANT PARCELA"))
        item = self.tabWid_obra.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "DATA CONTRATO"))
        item = self.tabWid_obra.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "VALOR VISITA"))
        item = self.tabWid_obra.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "INSC. IMOB."))
        item = self.tabWid_obra.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "ID CLIENTE 1"))
        item = self.tabWid_obra.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "ID CLIENTE 2"))
        item = self.tabWid_obra.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "ID CLIENTE 3"))
        item = self.tabWid_obra.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "ID CLIENTE 4"))
        item = self.tabWid_cli.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabWid_cli.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOME"))
        item = self.tabWid_cli.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.tabWid_cli.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RG"))
        item = self.tabWid_cli.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ENDEREÇO"))
        item = self.tabWid_cli.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "BAIRRO"))
        item = self.tabWid_cli.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "NUM"))
        item = self.tabWid_cli.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "CIDADE"))
        item = self.tabWid_cli.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ESTADO"))
        item = self.tabWid_cli.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "CEP"))
        item = self.tabWid_cli.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "NACIONALIDADE"))
        item = self.tabWid_cli.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "PROFISSÃO"))
        item = self.tabWid_cli.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "ESTADO CIVIL"))
        item = self.tabWid_cli.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "CELULAR"))
        item = self.tabWid_cli.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "EMAIL"))
        self.txt_searchrua.setPlaceholderText(_translate("MainWindow", "RUA DO TERRENO"))
        self.btn_search.setText(_translate("MainWindow", "⌕"))
        self.btn_search_2.setText(_translate("MainWindow", "⌕"))
        self.txt_searchnome.setPlaceholderText(_translate("MainWindow", "NOME DO CLIENTE"))
        self.txt_idobra.setPlaceholderText(_translate("MainWindow", "ID DA OBRA"))
        self.txt_idcli1.setPlaceholderText(_translate("MainWindow", "ID DO CLIENTE 1"))
        self.txt_idcli2.setPlaceholderText(_translate("MainWindow", "ID DO CLIENTE 2"))
        self.txt_idcli3.setPlaceholderText(_translate("MainWindow", "ID DO CLIENTE 3"))
        self.txt_idcli4.setPlaceholderText(_translate("MainWindow", "ID DO CLIENTE 4"))
        self.lbl_version.setText(_translate("MainWindow", "V 1.1"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">Created by Gustavo Lima</span></p></body></html>"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Doc()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
