# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 700)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setStyleSheet("color:rgb(200, 200, 255);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_popup = QtWidgets.QFrame(self.top_bar)
        self.frame_popup.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_popup.setStyleSheet("background-color: rgb(57, 173, 84);\n"
"border-radius:5px;")
        self.frame_popup.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_popup.setObjectName("frame_popup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_popup)
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_popup)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(35, 35, 35);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame_popup)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close_Image/Images/cil-x.png);\n"
"    background-position:center;\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame_popup)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_area = QtWidgets.QFrame(self.content)
        self.menu_area.setMaximumSize(QtCore.QSize(450, 550))
        self.menu_area.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 10px")
        self.menu_area.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menu_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_area.setObjectName("menu_area")
        self.logo = QtWidgets.QFrame(self.menu_area)
        self.logo.setGeometry(QtCore.QRect(119, 0, 211, 90))
        self.logo.setStyleSheet("background-image: url(:/Logo_yellow/Images/logorocha_360x90.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.lbl_welcome = QtWidgets.QLabel(self.menu_area)
        self.lbl_welcome.setGeometry(QtCore.QRect(85, 120, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(14)
        self.lbl_welcome.setFont(font)
        self.lbl_welcome.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_welcome.setObjectName("lbl_welcome")
        self.btn_cadobra = QtWidgets.QPushButton(self.menu_area)
        self.btn_cadobra.setGeometry(QtCore.QRect(80, 240, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cadobra.setFont(font)
        self.btn_cadobra.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_cadobra.setObjectName("btn_cadobra")
        self.btn_cliente = QtWidgets.QPushButton(self.menu_area)
        self.btn_cliente.setGeometry(QtCore.QRect(80, 180, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cliente.setFont(font)
        self.btn_cliente.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_cliente.setObjectName("btn_cliente")
        self.btn_makedoc = QtWidgets.QPushButton(self.menu_area)
        self.btn_makedoc.setGeometry(QtCore.QRect(80, 300, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_makedoc.setFont(font)
        self.btn_makedoc.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_makedoc.setObjectName("btn_makedoc")
        self.btn_edituser = QtWidgets.QPushButton(self.menu_area)
        self.btn_edituser.setGeometry(QtCore.QRect(80, 360, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_edituser.setFont(font)
        self.btn_edituser.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_edituser.setObjectName("btn_edituser")
        self.horizontalLayout.addWidget(self.menu_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setContentsMargins(0, 6, 4, 1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_version = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.lbl_version.setFont(font)
        self.lbl_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout_2.addWidget(self.lbl_version)
        self.lbl_lima = QtWidgets.QLabel(self.bottom)
        self.lbl_lima.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_lima.setObjectName("lbl_lima")
        self.verticalLayout_2.addWidget(self.lbl_lima)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "NOTA DE ATUALIZAÇÃO"))
        self.lbl_welcome.setText(_translate("MainWindow", "Bem vindo Rogério"))
        self.btn_cadobra.setText(_translate("MainWindow", "OBRAS E PROJETOS"))
        self.btn_cliente.setText(_translate("MainWindow", "CLIENTES"))
        self.btn_makedoc.setText(_translate("MainWindow", "CRIAR DOCUMENTOS"))
        self.btn_edituser.setText(_translate("MainWindow", "EDITAR USUÁRIO"))
        self.lbl_version.setText(_translate("MainWindow", "V 1.1"))
        self.lbl_lima.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">Created by Gustavo Lima</span></p></body></html>"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Menu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
