# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_obra.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Obra(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1039, 859)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setStyleSheet("color:rgb(200, 200, 255);\n"
"background-color: rgb(10, 10, 10);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 800))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 35))
        self.top_bar.setStyleSheet("")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_popup = QtWidgets.QFrame(self.top_bar)
        self.frame_popup.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_popup.setStyleSheet("background-color: rgb(57, 173, 84);\n"
"border-radius:5px;")
        self.frame_popup.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_popup.setObjectName("frame_popup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_popup)
        self.horizontalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_popup)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(35, 35, 35);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(self.frame_popup)
        self.pushButton.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-image: url(:/Close_Image/Images/cil-x.png);\n"
"    background-position:center;\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(35, 35, 35);\n"
"    color: rgb(255, 255, 127);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame_popup)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editocli_area = QtWidgets.QFrame(self.content)
        self.editocli_area.setMinimumSize(QtCore.QSize(0, 0))
        self.editocli_area.setMaximumSize(QtCore.QSize(950, 800))
        self.editocli_area.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"border-radius: 10px")
        self.editocli_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.editocli_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.editocli_area.setObjectName("editocli_area")
        self.logo = QtWidgets.QFrame(self.editocli_area)
        self.logo.setGeometry(QtCore.QRect(410, 0, 211, 90))
        self.logo.setStyleSheet("background-image: url(:/Logo_yellow/Images/logorocha_360x90.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.btn_return = QtWidgets.QPushButton(self.editocli_area)
        self.btn_return.setGeometry(QtCore.QRect(30, 20, 41, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(18)
        self.btn_return.setFont(font)
        self.btn_return.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_return.setObjectName("btn_return")
        self.txt_obralote = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obralote.setGeometry(QtCore.QRect(510, 330, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obralote.setFont(font)
        self.txt_obralote.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obralote.setMaxLength(32)
        self.txt_obralote.setObjectName("txt_obralote")
        self.txt_obraquarteirao = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obraquarteirao.setGeometry(QtCore.QRect(510, 390, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obraquarteirao.setFont(font)
        self.txt_obraquarteirao.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obraquarteirao.setMaxLength(32)
        self.txt_obraquarteirao.setObjectName("txt_obraquarteirao")
        self.txt_obranumero = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obranumero.setGeometry(QtCore.QRect(510, 270, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obranumero.setFont(font)
        self.txt_obranumero.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obranumero.setMaxLength(32)
        self.txt_obranumero.setObjectName("txt_obranumero")
        self.txt_id = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_id.setGeometry(QtCore.QRect(510, 90, 361, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_id.setFont(font)
        self.txt_id.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_id.setMaxLength(64)
        self.txt_id.setObjectName("txt_id")
        self.txt_obrabairro = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obrabairro.setGeometry(QtCore.QRect(510, 210, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obrabairro.setFont(font)
        self.txt_obrabairro.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obrabairro.setMaxLength(64)
        self.txt_obrabairro.setObjectName("txt_obrabairro")
        self.txt_obracidade = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obracidade.setGeometry(QtCore.QRect(730, 270, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obracidade.setFont(font)
        self.txt_obracidade.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obracidade.setMaxLength(32)
        self.txt_obracidade.setObjectName("txt_obracidade")
        self.btn_edit = QtWidgets.QPushButton(self.editocli_area)
        self.btn_edit.setGeometry(QtCore.QRect(330, 700, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_edit.setFont(font)
        self.btn_edit.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_edit.setObjectName("btn_edit")
        self.txt_obratipo = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obratipo.setGeometry(QtCore.QRect(730, 390, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obratipo.setFont(font)
        self.txt_obratipo.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obratipo.setMaxLength(32)
        self.txt_obratipo.setObjectName("txt_obratipo")
        self.txt_obraend = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obraend.setGeometry(QtCore.QRect(510, 150, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obraend.setFont(font)
        self.txt_obraend.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obraend.setMaxLength(64)
        self.txt_obraend.setObjectName("txt_obraend")
        self.txt_obraart = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obraart.setGeometry(QtCore.QRect(730, 450, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obraart.setFont(font)
        self.txt_obraart.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obraart.setMaxLength(32)
        self.txt_obraart.setObjectName("txt_obraart")
        self.btn_delete = QtWidgets.QPushButton(self.editocli_area)
        self.btn_delete.setGeometry(QtCore.QRect(30, 700, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        self.txt_obraquantparcela = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obraquantparcela.setGeometry(QtCore.QRect(730, 510, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obraquantparcela.setFont(font)
        self.txt_obraquantparcela.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obraquantparcela.setMaxLength(32)
        self.txt_obraquantparcela.setObjectName("txt_obraquantparcela")
        self.txt_obraquadra = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obraquadra.setGeometry(QtCore.QRect(730, 330, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obraquadra.setFont(font)
        self.txt_obraquadra.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obraquadra.setMaxLength(32)
        self.txt_obraquadra.setObjectName("txt_obraquadra")
        self.txt_obravalorparcela = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obravalorparcela.setGeometry(QtCore.QRect(510, 510, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obravalorparcela.setFont(font)
        self.txt_obravalorparcela.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obravalorparcela.setMaxLength(32)
        self.txt_obravalorparcela.setObjectName("txt_obravalorparcela")
        self.tabWid_obra = QtWidgets.QTableWidget(self.editocli_area)
        self.tabWid_obra.setGeometry(QtCore.QRect(10, 150, 491, 471))
        self.tabWid_obra.setStyleSheet("QTableWidget{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QTableWidget:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QTableWidget:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QTableWidget:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"    padding: 5px;\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    gridline-color: rgb(255, 165, 24);\n"
"}\n"
"\n"
"QTableWidget QTableCornerButton {\n"
"    background-color: rgb(30, 30, 30); \n"
"}\n"
"\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: rgb(30, 30, 30);\n"
"}\n"
"")
        self.tabWid_obra.setObjectName("tabWid_obra")
        self.tabWid_obra.setColumnCount(19)
        self.tabWid_obra.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabWid_obra.setHorizontalHeaderItem(18, item)
        self.txt_obravalorvisita = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obravalorvisita.setGeometry(QtCore.QRect(730, 570, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obravalorvisita.setFont(font)
        self.txt_obravalorvisita.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obravalorvisita.setMaxLength(32)
        self.txt_obravalorvisita.setObjectName("txt_obravalorvisita")
        self.txt_obradatacontrato = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obradatacontrato.setGeometry(QtCore.QRect(510, 570, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obradatacontrato.setFont(font)
        self.txt_obradatacontrato.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obradatacontrato.setMaxLength(32)
        self.txt_obradatacontrato.setObjectName("txt_obradatacontrato")
        self.txt_obraareaterreno = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_obraareaterreno.setGeometry(QtCore.QRect(510, 450, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_obraareaterreno.setFont(font)
        self.txt_obraareaterreno.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_obraareaterreno.setMaxLength(32)
        self.txt_obraareaterreno.setObjectName("txt_obraareaterreno")
        self.txt_rua = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_rua.setGeometry(QtCore.QRect(10, 90, 431, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_rua.setFont(font)
        self.txt_rua.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_rua.setMaxLength(32)
        self.txt_rua.setObjectName("txt_rua")
        self.btn_add = QtWidgets.QPushButton(self.editocli_area)
        self.btn_add.setGeometry(QtCore.QRect(630, 700, 280, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.btn_copy = QtWidgets.QPushButton(self.editocli_area)
        self.btn_copy.setGeometry(QtCore.QRect(880, 90, 61, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_copy.setFont(font)
        self.btn_copy.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"    font: 18pt ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_copy.setObjectName("btn_copy")
        self.txt_idcli3 = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_idcli3.setGeometry(QtCore.QRect(510, 630, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli3.setFont(font)
        self.txt_idcli3.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli3.setMaxLength(32)
        self.txt_idcli3.setObjectName("txt_idcli3")
        self.txt_idcli4 = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_idcli4.setGeometry(QtCore.QRect(730, 630, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli4.setFont(font)
        self.txt_idcli4.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli4.setMaxLength(32)
        self.txt_idcli4.setObjectName("txt_idcli4")
        self.txt_idcli2 = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_idcli2.setGeometry(QtCore.QRect(290, 630, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli2.setFont(font)
        self.txt_idcli2.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli2.setMaxLength(32)
        self.txt_idcli2.setObjectName("txt_idcli2")
        self.txt_idcli1 = QtWidgets.QLineEdit(self.editocli_area)
        self.txt_idcli1.setGeometry(QtCore.QRect(70, 630, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        font.setPointSize(10)
        self.txt_idcli1.setFont(font)
        self.txt_idcli1.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"QLineEdit:hover{\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px solid rgb(255, 207, 0);\n"
"    color: rgb(200, 200, 200);\n"
"}")
        self.txt_idcli1.setMaxLength(32)
        self.txt_idcli1.setObjectName("txt_idcli1")
        self.btn_search = QtWidgets.QPushButton(self.editocli_area)
        self.btn_search.setGeometry(QtCore.QRect(450, 90, 51, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton{\n"
"    background-color:rgb(50, 50, 50);\n"
"    border:2px solid rgb(60, 60, 60);\n"
"    border-radius:5px;\n"
"    font: 18pt ;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70, 70, 70);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgb(250, 230, 0);\n"
"    border: 2px solid rgb(255, 165, 24);\n"
"    color: rgb(35, 35, 35);\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.editocli_area)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 35))
        self.bottom.setStyleSheet("background-color: rgb(15, 15, 15);")
        self.bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bottom)
        self.verticalLayout_2.setContentsMargins(0, 0, 6, 1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_version = QtWidgets.QLabel(self.bottom)
        self.lbl_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_version.setObjectName("lbl_version")
        self.verticalLayout_2.addWidget(self.lbl_version)
        self.lbl_created = QtWidgets.QLabel(self.bottom)
        font = QtGui.QFont()
        font.setFamily("Quicksand")
        self.lbl_created.setFont(font)
        self.lbl_created.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_created.setObjectName("lbl_created")
        self.verticalLayout_2.addWidget(self.lbl_created)
        self.verticalLayout.addWidget(self.bottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Edit Client"))
        self.label.setText(_translate("MainWindow", "EDITADO"))
        self.btn_return.setText(_translate("MainWindow", "↩"))
        self.txt_obralote.setPlaceholderText(_translate("MainWindow", "LOTE"))
        self.txt_obraquarteirao.setPlaceholderText(_translate("MainWindow", "QUARTEIRÃO"))
        self.txt_obranumero.setPlaceholderText(_translate("MainWindow", "NUMERO"))
        self.txt_id.setPlaceholderText(_translate("MainWindow", "DIGITE O ID"))
        self.txt_obrabairro.setPlaceholderText(_translate("MainWindow", "BAIRRO"))
        self.txt_obracidade.setPlaceholderText(_translate("MainWindow", "CIDADE"))
        self.btn_edit.setText(_translate("MainWindow", "EDIT"))
        self.txt_obratipo.setPlaceholderText(_translate("MainWindow", "TIPO DE PROJETO"))
        self.txt_obraend.setPlaceholderText(_translate("MainWindow", "ENDEREÇO"))
        self.txt_obraart.setPlaceholderText(_translate("MainWindow", "ART DO PROJETO"))
        self.btn_delete.setText(_translate("MainWindow", "DELETE"))
        self.txt_obraquantparcela.setPlaceholderText(_translate("MainWindow", "QUANT. PARCELA"))
        self.txt_obraquadra.setPlaceholderText(_translate("MainWindow", "QUADRA"))
        self.txt_obravalorparcela.setPlaceholderText(_translate("MainWindow", "VALOR DA PARCELA"))
        item = self.tabWid_obra.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tabWid_obra.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ENDEREÇO"))
        item = self.tabWid_obra.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "BAIRRO"))
        item = self.tabWid_obra.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NUMERO"))
        item = self.tabWid_obra.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CIDADE"))
        item = self.tabWid_obra.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "LOTE"))
        item = self.tabWid_obra.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "QUADRA"))
        item = self.tabWid_obra.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "QUARTEIRÃO"))
        item = self.tabWid_obra.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.tabWid_obra.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "AREA"))
        item = self.tabWid_obra.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "ART"))
        item = self.tabWid_obra.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "VALOR PARCELA"))
        item = self.tabWid_obra.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "QUANT PARCELA"))
        item = self.tabWid_obra.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "DATA CONTRATO"))
        item = self.tabWid_obra.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "VALOR VISITA"))
        item = self.tabWid_obra.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "ID CLIENTE 1"))
        item = self.tabWid_obra.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "ID CLIENTE 2"))
        item = self.tabWid_obra.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "ID CLIENTE 3"))
        item = self.tabWid_obra.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "ID CLIENTE 4"))
        self.txt_obravalorvisita.setPlaceholderText(_translate("MainWindow", "VALOR VISITA TÉC."))
        self.txt_obradatacontrato.setPlaceholderText(_translate("MainWindow", "DATA DO CONTRATO"))
        self.txt_obraareaterreno.setPlaceholderText(_translate("MainWindow", "AREA DO TERRENO"))
        self.txt_rua.setPlaceholderText(_translate("MainWindow", "RUA DO TERRENO"))
        self.btn_add.setText(_translate("MainWindow", "ADD"))
        self.btn_copy.setText(_translate("MainWindow", "✍"))
        self.txt_idcli3.setPlaceholderText(_translate("MainWindow", "ID CLIENTE 3"))
        self.txt_idcli4.setPlaceholderText(_translate("MainWindow", "ID CLIENTE 4"))
        self.txt_idcli2.setPlaceholderText(_translate("MainWindow", "ID CLIENTE 2"))
        self.txt_idcli1.setPlaceholderText(_translate("MainWindow", "ID CLIENTE 1"))
        self.btn_search.setText(_translate("MainWindow", "⌕"))
        self.lbl_version.setText(_translate("MainWindow", "V 1.1"))
        self.lbl_created.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" vertical-align:super;\">Created by Gustavo Lima</span></p></body></html>"))
import file_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Obra()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
